#端口号
server:
  port: 8080
spring:
  datasource:
    username: root
    password: qianwilson@91
    url: jdbc:mysql://120.77.81.64:3306/admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true   #打印sql
    hibernate:
      ddl-auto: update  #更新数据库
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#redis连接配置
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 8
        min-idle: 8
      shutdown-timeout: 100
  
  
