#端口号
server:
  port: 8080
spring:
  datasource:
    username: root
    password: wilson443158
    url: jdbc:mysql://localhost:3306/sc?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: mysql
    show-sql: true   #打印sql
    hibernate:
      ddl-auto: update  #更新数据库
      
    
  
  
