server:
  port: 9090

zuul:
  routes:
    token:
      url: http://localhost:9080
    order:
      url: http://localhost:9060
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
    - limit: 2
      quota: 1
      refresh-interval: 3
      type:
      - url
      - httpmethod
       
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/resource?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: wilson443158
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    
security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9080/oauth/token_key
    client:
      client-id: gateway
      client-secret: 12345

