server:
  port: 80
spring:
  activemq:
    #broker-url: tcp://localhost:61616
    broker-url: failover:(tcp://172.17.27.45:50501,tcp://172.17.27.46:50501,tcp://172.17.27.47:50501)
    packages:
      trust-all: true
    user: activemq_cncp
    password: vy5T6CXeQ00fTHLR
  jms:
    pub-sub-domain: false #true为topic模式（发布与订阅）false为点对点模式（queue）