server:
  port: 80
spring:
  activemq:
    #broker-url: tcp://localhost:61616
    broker-url: failover:(tcp://localhost:61616,tcp://localhost:61617,tcp://localhost:61618)
    packages:
      trust-all: true
    user: admin
    password: admin
  jms:
    pub-sub-domain: true #true为topic模式（发布与订阅）false为点对点模式（queue）