#net.devh.boot.grpc.client.config.GrpcServerProperties
grpc:
  client:
    userClient:
      negotiationType: TLS #证书验证的两种模式PLAINTEXT、TLS
      address: static://localhost:9091
      security:
        trust-cert-collection: classpath:keys/trusted-servers-collection
        private-key: classpath:keys/client2.key
        certificate-chain: classpath:keys/client.pem
        authority-override: SERVER
        client-auth-enabled: true
server:
  port: 8082
spring:
  profiles:
    active: dev
  application:
    name: grcp-client