grpc:
  server:
    port: 9091
    in-process-name: grpc-server
    keep-alive-timeout: 60
    keep-alive-time: 60
    security:
      enabled: true
      client-auth: REQUIRE
      certificate-chain: classpath:keys/server.pem
      private-key: classpath:keys/server2.key
      trust-cert-collection: classpath:keys/trusted-clients-collection
spring:
  profiles:
    active: dev
  application:
    name: grpc-server
  datasource:
    name: dev
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: wilson443158
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: false
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
logging:
  level:
    root: INFO
    com.sun.mapper: DEBUG